// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ULMSRepository.Context;

namespace ULMSRepository.Migrations
{
    [DbContext(typeof(ULMSLoansContext))]
    [Migration("20180801205308_Mig")]
    partial class Mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ULMSLoansDomain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualPaymentDate");

                    b.Property<double>("Amount");

                    b.Property<double>("AmountPaidThusFar");

                    b.Property<int>("CreatedBy");

                    b.Property<int>("CreatedOn");

                    b.Property<int>("CurrentStatus");

                    b.Property<int>("CustomerId");

                    b.Property<bool>("FullyPaid");

                    b.Property<double>("InterestRate");

                    b.Property<double>("InterestValue");

                    b.Property<int>("ModifiedBy");

                    b.Property<int>("ModifiedOn");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<double>("Profit");

                    b.Property<double>("TotalAmountToBePaid");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
